### ISSUE TITLE
Android Crash After set Call back listener

### ISSUE THREAD

**Issue by bhushanvyas** [bluecats/bluecats-android-sdk#12]
WHen we set this two line in my activity onCreate
  BlueCatsSDK.startPurringWithAppToken(getApplicationContext(), Constants.APP_TOKEN);
      
        final BCBeaconManager beaconManager = new BCBeaconManager();
        beaconManager.registerCallback( mBeaconManagerCallback );

Third Line throw following  error:

java.lang.NoSuchMethodError: no static or non-static method "Lcom/bluecats/sdk/BCBeaconCommand;.nativeConverter(Ljava/lang/Object;)Ljava/lang/Object;"
            at java.lang.Runtime.nativeLoad(Native Method)
            at java.lang.Runtime.doLoad(Runtime.java:421)
            at java.lang.Runtime.loadLibrary(Runtime.java:362)
            at java.lang.System.loadLibrary(System.java:526)
            at com.bluecats.sdk.BlueCatsSDKService.<clinit>(SourceFile:861)
            at com.bluecats.sdk.BCBeaconManager.registerCallback(SourceFile:45)
            at au.coyote.activity.DashboardHomeActivity.bindBeacons(DashboardHomeActivity.java:330)
            at au.coyote.activity.DashboardHomeActivity.bluetoothResponsibleMethod(DashboardHomeActivity.java:276)
            at au.coyote.activity.DashboardHomeActivity.onCreate(DashboardHomeActivity.java:468)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by henrybluecats** [comment]
Hey bhushanvyas,
Thanks for your information, Could you provide the following information:
1. Android version of your mobile phone
2. Android studio version
3. compileSdkVersion and buildToolsVersion in build.gradle of your app
4. BlueCats SDK version number
5. Java version that your Android Studio is using to build your app

Thanks,
Henry

**Comment by bhushanvyas** [comment]
Android version of your mobile phone                                                  :- S4 Api 19
.Android studio version                                                                          :- 1.3
compileSdkVersion and buildToolsVersion in build.gradle of your app :-  24
BlueCats SDK version number                                                              :-  sdk:2.0.1
Java version that your Android Studio is using to build your app          :-  1.8

**Comment by henrybluecats** [comment]
have you tried the latest Android studio?

**Comment by bhushanvyas** [comment]
yes but same issue occure

**Comment by henrybluecats** [comment]
Hey,
please check if you have both old sdk and v2.0.1 in the same project. To doing that, just find if you have bluecats_sdk.jar in libs folder and libbluecats_sdk.so in src/main/jniLibs/<ABI> folders, if yes, delete them and follow the instructions(https://github.com/bluecats/bluecats-android-sdk#android-sdk-installation) step 1 and step 2 to integrate our sdk.

Thanks,
Henry 
henry@bluecats.com
