### ISSUE TITLE
Crash on BT/Location turn off.

### ISSUE THREAD

**Issue by AlexxS** [bluecats/bluecats-android-sdk#3]
When the app is in background when I turn off BT and location the app crashes with exception:
   java.lang.IllegalStateException: BT Adapter is not turned ON
            at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
            at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:144)
            at com.bluecats.sdk.ak.p(SourceFile:205)
            at com.bluecats.sdk.ak.f(SourceFile:180)
            at com.bluecats.sdk.ak.j(SourceFile:220)
            at com.bluecats.sdk.ai.c(SourceFile:215)
            at com.bluecats.sdk.ai.a(SourceFile:197)
            at com.bluecats.sdk.ai.o(SourceFile:223)
            at com.bluecats.sdk.ai.a(SourceFile:218)
            at com.bluecats.sdk.ai$1.run(SourceFile:239)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
I can't handle this exception.
I check the BT and location on app resume, but it's not very good to have the app crashed when it's in background. 
Could you please stop throwing/surround with try/catch this exception or make some setter if it should be thrown?

**Comment by henrybluecats** [comment]
Hi Alex,
we have fixed this issue, and will release soon.

Thanks,
Henry

**Comment by theporkchopexpress** [comment]
This issue has been resolved in release 1.10.2. Please advise of any further issues.

Cheers,
Darren
